import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import Image from "next/image";
import Chart from "./features/Chart";
import tmpImage from "../public/favicon.ico";
export default function Home() {
  const BASE_URL =
    "https://api.coingecko.com/api/v3/coins/bitcoin?localization=false&tickers=true&market_data=true&community_data=false&developer_data=false&sparkline=false";
  const PRICE_TIME_URL =
    "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=jpy&days=90";
  const [coinData, setCoinData] = useState<any>({});
  const [coinPriceData, setCoinPriceData] = useState<any>({});
  useEffect(() => {
    const getCoinData = () => {
      axios.get(`${BASE_URL}`).then((response) => {
        setCoinData(response.data);
        console.log(response.data);
      });
      axios.get(`${PRICE_TIME_URL}`).then((response) => {
        setCoinPriceData(response.data);
      });
    };
    getCoinData();
  }, []);
  return (
    <div className="bg-gray-900 min-h-screen min-w-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-white">
        <h2>{coinData.hasOwnProperty("name") ? coinData.name : "Error"}</h2>
        <h2>
          {coinPriceData.hasOwnProperty("prices")
            ? Math.ceil(coinPriceData.prices[0][1])
            : "Error"}{" "}
          JPY
        </h2>
        <h2>
          {coinPriceData.hasOwnProperty("prices")
            ? Math.ceil(coinPriceData.prices[1][1])
            : "Error"}{" "}
          JPY
        </h2>
        <h2>
          {coinPriceData.hasOwnProperty("prices")
            ? coinPriceData.prices?.length
            : "Error"}{" "}
        </h2>
        {/* <Image
          alt="image"
          src={
            coinData.hasOwnProperty("image") ? coinData.image.large : tmpImage
          }
          width="80"
          height="80"
        /> */}
        <Chart />
      </main>
    </div>
  );
}
